<?php
return [
    // ========== PRODUCTOS ORIGINALES ==========
    ["img" => "images/productos/teclado68.jpg", "nombre" => "Teclado Magnético Mecánico Aula Win68 HE", "desc" => "Precisión de pulsación de hasta 0,02 mm, superando los 0,04 mm de la versión estándar.", "tag" => "⭐ Recomendado", "link" => "https://meli.la/2RyuhEb"],
    ["img" => "images/productos/teclado68shark.jpg", "nombre" => "Teclado Gamer Attack Shark X68HE", "desc" => "Teclado magnético de 8 KHz con cable al 60 % con precisión RT de 0,01 mm, compatible con RT/Snap Tap/DKS/MT/TGL.", "tag" => "🔥 Popular", "link" => "https://meli.la/1TnCgHw"],
        ["img" => "images/productos/mouse.jpg", "nombre" => "Mouse gamer inalámbrico Logitech G Serie Lightspeed G305", "desc" => "Gracias a un eficiente diseño mecánico, G305 pesa solo 99 gramos, lo que le proporciona una gran capacidad de maniobra.", "tag" => "🔥 Popular", "link" => "https://meli.la/1Z2qvWf"],
    ["img" => "images/productos/teclado.jpg", "nombre" => "Teclado gamer Redragon Kumara K552 QWERTY Red", "desc" => "Su construcción está realizada sobre ABS reforzado y placa de acero.", "tag" => "⭐ Recomendado", "link" => "https://meli.la/1K9Joh5"],
    ["img" => "images/productos/auris.jpg", "nombre" => "Auriculares Gamer Inalámbricos Redragon Zeus Pro H510-pro Usb/bluetooth 7.1 Color Negro", "desc" => "Disfrute de una calidad de sonido real y sin pérdidas con la tecnología de sonido envolvente 7.1", "tag" => "🔥 Popular", "link" => "https://meli.la/2mkcxdo"],
    ["img" => "images/productos/rx7600.jpg", "nombre" => "Placa De Video Amd Radeon XFX Speedster RX 7600 Qick 308 8gb GDDR6", "desc" => "Con su avanzado chipset AMD RX 7600 y una generosa memoria de 8 GB GDDR6, esta tarjeta está diseñada para ofrecer una experiencia de juego fluida y detallada.", "tag" => "⭐ Recomendado", "link" => "https://meli.la/2PKAyRi"],
    ["img" => "images/productos/mando.jpg", "nombre" => "Sony PlayStation DualSens Joystick inalámbrico", "desc" => "Compatible con PlayStation 5 y sistemas operativos Windows, el DualSense incluye un altavoz integrado y un touchpad que te permiten interactuar de manera intuitiva con tus juegos.", "tag" => "🔥 Popular", "link" => "https://meli.la/1xFmBLd"],

    // ========== NUEVOS PRODUCTOS GAMER ==========
    ["img" => "images/productos/monitor_asus.jpg", "nombre" => "Monitor Gamer ASUS TUF VG249Q 24'' 144Hz", "desc" => "Pantalla IPS de 1ms, FreeSync Premium, baja luz azul. Ideal para competitivo.", "tag" => "🔥 Popular", "link" => "https://meli.la/2JPmcvH"],
        ["img" => "images/productos/superlight2.jpg", "nombre" => "Mouse Gamer Inalámbrico Logitech G Pro X Superlight 2 Blanco", "desc" => "Sensor HERO 2 óptico con hasta 44000 DPI ofrece precisión extrema en juegos competitivos.", "tag" => "🏆 Más vendido", "link" => "https://meli.la/2ogg9jp"],
    ["img" => "images/productos/teclado_hyperx.jpg", "nombre" => "Teclado Mecánico HyperX Alloy Origins Red Switch", "desc" => "Switch lineales HyperX Red, RGB personalizable, placa de aluminio.", "tag" => "⭐ Recomendado", "link" => "https://meli.la/1Q5cBaN"],
    ["img" => "images/productos/auricular_razer.jpg", "nombre" => "Auriculares Razer BlackShark V2 X", "desc" => "Sonido envolvente 7.1, almohadillas de espuma viscoelástica, micrófono cardioide.", "link" => "https://meli.la/2qXqJpU"],
    ["img" => "images/productos/mouse_glorious.jpg", "nombre" => "Mouse Glorious Model O- (Minus) Ultraligero", "desc" => "Peso de 58 gramos, cable flexible ascendente, sensor Pixart 3360.", "tag" => "🔥 Popular", "link" => "https://meli.la/1Qj7EFs"],
    ["img" => "images/productos/silla_corsair.jpg", "nombre" => "Silla Gamer Corsair TC100 Relaxed", "desc" => "Espuma de alta densidad, reposabrazos 4D, respaldo hasta 160 grados.", "link" => "https://meli.la/28NiYAM"],
    ["img" => "images/productos/monitor_samsung.jpg", "nombre" => "Monitor Curvo Samsung Odyssey G5 27'' 144Hz", "desc" => "Curvatura 1000R, panel VA, 1ms MPRT, HDR10.", "tag" => "🏆 Más vendido", "link" => "https://meli.la/172mPHm"],
    ["img" => "images/productos/teclado_logitech.jpg", "nombre" => "Teclado Logitech G915 TKL Lightspeed", "desc" => "Inalámbrico, switches GL táctiles, RGB LIGHTSYNC, batería de 30h.", "link" => "https://meli.la/1Lp8HGw"],
    ["img" => "images/productos/auricular_steelseries.jpg", "nombre" => "Auriculares SteelSeries Arctis Nova 7", "desc" => "Controladores magnéticos de neodimio de alta calidad para un paisaje sonoro ultradetallado.", "tag" => "⭐ Recomendado", "link" => "https://meli.la/244gdEb"],
    ["img" => "images/productos/mouse_logitech_gpro.jpg", "nombre" => "Mouse Logitech G Pro X Superlight", "desc" => "Inalámbrico, 63 gramos, sensor HERO 25K, 5 botones programables.", "link" => "https://meli.la/16QbGSm"],
    ["img" => "images/productos/gabinete_noganet.jpg", "nombre" => "Gabinete Noganet Stormer", "desc" => "Poderoso Gabinete Gamer con 3 Coolers con LEDS rojos.", "tag" => "🔥 Popular", "link" => "https://meli.la/1xUMfWH"],
    ["img" => "images/productos/auricular_hyperx.jpg", "nombre" => "Auriculares HyperX Cloud Stinger 2", "desc" => "Sonido inmersivo, diadema ajustable, almohadillas suaves, peso ligero.", "tag" => "🏆 Más vendido", "link" => "https://meli.la/2e1jMst"],
    ["img" => "images/productos/teclado_redragon_k580.jpg", "nombre" => "Teclado Redragon K580 VATA RGB", "desc" => "Switches mecánicos Outemu, teclado numérico, construcción metálica.", "link" => "https://meli.la/11WAwMD"]
];